SET BIN_EXE=cmake-build-debug\jpg_decoder.exe
SET IMAGES_DIR=images
%BIN_EXE% %IMAGES_DIR%\airplane30.jpg
%BIN_EXE% %IMAGES_DIR%\airplane80.jpg
%BIN_EXE% %IMAGES_DIR%\arctichare30.jpg
%BIN_EXE% %IMAGES_DIR%\arctichare80.jpg
%BIN_EXE% %IMAGES_DIR%\baboon30.jpg
%BIN_EXE% %IMAGES_DIR%\baboon80.jpg
%BIN_EXE% %IMAGES_DIR%\cat30.jpg
%BIN_EXE% %IMAGES_DIR%\cat80.jpg
%BIN_EXE% %IMAGES_DIR%\fruits30.jpg
%BIN_EXE% %IMAGES_DIR%\fruits80.jpg
%BIN_EXE% %IMAGES_DIR%\frymire30.jpg
%BIN_EXE% %IMAGES_DIR%\frymire80.jpg
%BIN_EXE% %IMAGES_DIR%\girl30.jpg
%BIN_EXE% %IMAGES_DIR%\girl80.jpg
%BIN_EXE% %IMAGES_DIR%\lena30.jpg
%BIN_EXE% %IMAGES_DIR%\lena80.jpg
%BIN_EXE% %IMAGES_DIR%\monarch30.jpg
%BIN_EXE% %IMAGES_DIR%\monarch80.jpg
%BIN_EXE% %IMAGES_DIR%\peppers30.jpg
%BIN_EXE% %IMAGES_DIR%\peppers80.jpg
%BIN_EXE% %IMAGES_DIR%\pool30.jpg
%BIN_EXE% %IMAGES_DIR%\pool80.jpg
%BIN_EXE% %IMAGES_DIR%\sails30.jpg
%BIN_EXE% %IMAGES_DIR%\sails80.jpg
%BIN_EXE% %IMAGES_DIR%\serrano30.jpg
%BIN_EXE% %IMAGES_DIR%\serrano80.jpg
%BIN_EXE% %IMAGES_DIR%\tulips30.jpg
%BIN_EXE% %IMAGES_DIR%\tulips80.jpg
%BIN_EXE% %IMAGES_DIR%\watch30.jpg
%BIN_EXE% %IMAGES_DIR%\watch80.jpg